### ISSUE TITLE
Custom biome sizes?

### ISSUE THREAD

**Issue by usevalue** [hoqhuuep/IslandCraft#10]
Interesting plugin, but I would like to be able to customise biome sizes.  Personally, I would love a world with much much larger oceans.

**Comment by hoqhuuep** [comment]
Have a play with the numbers in your plugins/IslandCraft/config.yml file:
https://github.com/hoqhuuep/IslandCraft/blob/master/IslandCraft-Core/src/main/resources/config.yml

Specifically you need to change this line:
`island-distribution: com.github.hoqhuuep.islandcraft.core.HexagonalIslandDistribution 288 32`


288 is the size of the islands (in blocks) and 32 is the size of the oceans between the islands (also in blocks). Try increasing the size of the oceans to, say, 192 for much larger oceans:
`island-distribution: com.github.hoqhuuep.islandcraft.core.HexagonalIslandDistribution 288 192`

Let me know how you go :-)

**Comment by usevalue** [comment]
Ah, a most splendid case of RTFM.  I've been playing with it a bit.  Ended up increasing the ocean size, as you suggested, as well as adding in an "ocean island" for a few extra gaps.  The tiled look still feels odd to me, but I'm getting the hang of how you're doing things.  I'd like to write up a custom distribution class with a bit more scattered feel to it...  Hmm.  Interesting stuff, mate.  I can see myself obsessing about this for some time.  Oh dear...

**Comment by hoqhuuep** [comment]
Yeah. I've thought quite a bit about a good way to get a more scattered distribution. The best I can come up with is to use something like the hexagonal distribution but offset each island by a random amount in x and z. Would probably work OK I think. Glad to hear you've figured out the config :-)
