### ISSUE TITLE
Plugin not working on 1.9.4 servers

### ISSUE THREAD

**Issue by EnDoSiA** [hoqhuuep/IslandCraft#13]
` [Server thread/INFO]: [IslandCraft] Enabling IslandCraft v1.0.4
[Server thread/ERROR]: [IslandCraft] IslandCraft does not currently support this CraftBukkit version
 [Server thread/ERROR]: [IslandCraft] Check for updates at http://dev.bukkit.org/bukkit-plugins/islandcraft/`

Plugin not working on 1.9.4 please fix

**Comment by hoqhuuep** [comment]
Thanks for the heads up! I've pushed out an update. It'll be on BukkitDev as soon as it's approved, or you can grab it here: https://github.com/hoqhuuep/IslandCraft/releases/tag/v1.0.5
