### ISSUE TITLE
Plugin not working on 1.10 servers

### ISSUE THREAD

**Issue by EnDoSiA** [hoqhuuep/IslandCraft#14]
[Server thread/INFO]: [IslandCraft] Enabling IslandCraft v1.0.5 
[Server thread/ERROR]: [IslandCraft] IslandCraft does not currently support this CraftBukkit version [Server thread/ERROR]: [IslandCraft] Check for updates at http://dev.bukkit.org/bukkit-plugins/islandcraft/

Plugin not working on 1.10 please fix

**Comment by hoqhuuep** [comment]
Thanks for the reminder! I'll get on it when I can!

**Comment by hoqhuuep** [comment]
Would you like to test this for me before I push to BukkitDev?

https://github.com/hoqhuuep/IslandCraft/releases/tag/v1.0.6
