### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by Platinteufel** [hoqhuuep/IslandCraft#17]
Hey hoqhuuep,

is it possible to push an IslandCraft version for CB 1.11 in the next weeks? Thank you! ;)
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-11-released.193887/
https://www.spigotmc.org/threads/bukkit-1-11-api-draft.193437/

**Comment by hoqhuuep** [comment]
Should be up on BukkitDev as soon as the file is approved. If you can't wait, you can also grab it from GitHub. https://github.com/hoqhuuep/IslandCraft/releases/tag/v1.0.7

Also, please remember to backup your world before updating!!!

**Comment by Platinteufel** [comment]
Thanks! ;-)
