### ISSUE TITLE
Update to Spigot 1.8

### ISSUE THREAD

**Issue by SlimaKCoder** [hoqhuuep/IslandCraft#2]
Can you update IslandCraft to support Spigot 1.8?

**Comment by SlimaKCoder** [comment]
We still waiting ;/

**Comment by hoqhuuep** [comment]
I know! Sorry :( Will get to it when I can...

**Comment by Zillew** [comment]
Really hoping for an update soon, wanting to expand my world do 15Ks but I can't without the generator working :S

**Comment by SlimaKCoder** [comment]
10 years later.... :P

**Comment by SlimaKCoder** [comment]
100 years later... ;P

**Comment by hoqhuuep** [comment]
1000 years later.. ;P

It's uploaded, just awaiting approval now... Should be able to download it from here in the next couple days: http://dev.bukkit.org/bukkit-plugins/islandcraft/files/

Really sorry about the wait! Hard to get into the mood for programming at home when I spend all day doing it at work. Let me know if you have any issues getting it going.

**Comment by hoqhuuep** [comment]
Grab it while it's hot!
http://dev.bukkit.org/bukkit-plugins/islandcraft/files/

**Comment by SlimaKCoder** [comment]
Thx ;)
