### ISSUE TITLE
Update to Spigot 1.12

### ISSUE THREAD

**Issue by Platinteufel** [hoqhuuep/IslandCraft#22]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12.246398/

Many thanks in advance! :)

**Comment by jeffmthomas** [comment]
I second this.  I am trying to see if I can get it working.

**Comment by hoqhuuep** [comment]
I'll see what I can do. Been quite a while since I last worked on this!

**Comment by hoqhuuep** [comment]
Can you please test this for me? As always, please backup everything before updating!

https://github.com/hoqhuuep/IslandCraft/releases/tag/v1.0.8

If you don't report any issues in the next few days, I'll push it to BukkitDev.

**Comment by edwardteach42** [comment]
I will let you know how it works.  Thanks! I was just trying to figure out the ebean issue when I noticed your push.

**Comment by edwardteach42** [comment]
I have not noticed any issues on my server.  When the plugin was disabled, some of my oceans generated using the default generator.  Is there any way to easily make them oceans again?

**Comment by hoqhuuep** [comment]
Thanks for testing! Sounds like you need to load up the world in MCEdit and delete those chunks.

**Comment by hoqhuuep** [comment]
Has been released https://dev.bukkit.org/projects/islandcraft/files/2437434
Closing this issue.
