### ISSUE TITLE
Generating a new world?

### ISSUE THREAD

**Issue by gravestristen** [hoqhuuep/IslandCraft#6]
i changed it to this and deleted the server world and when it loaded the generation didn't work, how do you change it?
worlds:
  # By default IslandCraft is enabled on "world".
  # You can change the world name here or even add more than one world

**Comment by hoqhuuep** [comment]
Cold you please provide your full configuration file?

**Comment by hoqhuuep** [comment]
Closing as it's been 6 months. Feel free to re-open or raise another issue if you are still having problems ;-)
